server:
  port: 90
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.162:8848  #nacos注册中心地址
    gateway:
      routes:
        - id: prodpct
          uri: lb://kunmall-product #配注册中心服务名
          predicates:
            - Path=/api/product/**
        - id: coupon
          uri: https://www.baidu.com
          predicates:
            - Query=url,bai.
logging:
  level:
    com.kunmall: debug