server:
  port: 90

spring:
  application:
    name: kunmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.10:8848  #nacos注册中心地址
    gateway:
      routes:
        - id: coupon
          uri: https://www.baidu.com
          predicates:
            - Query=url,bai.
        - id: test2
          uri: xxx
          predicates:
            - Query=url,test.


logging:
  level:
    com.kunmall: debug