server:
  port: 90
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.9:8848  #nacos注册中心地址
    gateway:
      routes:
        - id: product_route
          uri: lb://kunmall-product #配注册中心服务名
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

logging:
  level:
    com.kunmall: debug